CREATE TABLE customers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       varchar(320) NOT NULL UNIQUE,
    full_name   varchar(200) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         varchar(64) NOT NULL UNIQUE,
    name        varchar(200) NOT NULL,
    price       numeric(19, 2) NOT NULL CHECK (price >= 0),
    stock       integer NOT NULL CHECK (stock >= 0),
    version     bigint NOT NULL DEFAULT 0,
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE orders (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      bigint NOT NULL REFERENCES customers (id),
    idempotency_key  varchar(100) NOT NULL,
    status           varchar(24) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
    total_amount     numeric(19, 2) NOT NULL CHECK (total_amount >= 0),
    created_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (customer_id, idempotency_key)
);

CREATE INDEX ix_orders_customer_created
    ON orders (customer_id, created_at DESC, id DESC);
CREATE INDEX ix_orders_status_created
    ON orders (status, created_at DESC);

CREATE TABLE order_items (
    order_id              bigint NOT NULL REFERENCES orders (id),
    line_no               integer NOT NULL,
    product_id            bigint NOT NULL REFERENCES products (id),
    product_name_snapshot varchar(200) NOT NULL,
    unit_price            numeric(19, 2) NOT NULL CHECK (unit_price >= 0),
    quantity              integer NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (order_id, line_no)
);

CREATE INDEX ix_items_product ON order_items (product_id);

CREATE TABLE outbox_events (
    id              uuid PRIMARY KEY,
    aggregate_type  varchar(80) NOT NULL,
    aggregate_id    varchar(80) NOT NULL,
    event_type      varchar(120) NOT NULL,
    payload         jsonb NOT NULL,
    occurred_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
    published_at    timestamptz
);

CREATE INDEX ix_outbox_unpublished
    ON outbox_events (occurred_at)
    WHERE published_at IS NULL;
