spring.application.name=observability-concurrency-lab
spring.threads.virtual.enabled=true
spring.main.keep-alive=true
management.endpoints.web.exposure.include=health,metrics,prometheus
management.observations.key-values.stack=learning

